# Generated by Django 5.1.5 on 2025-02-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
