name: Django workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest  # Utiliser Windows au lieu d'Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "asgiref<3.8"
          pip install "dask<2022.0.0"
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8

      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report

      - name: Run Django tests
        run: python manage.py test
