name: Django workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest  # Utiliser Windows au lieu d'Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          submodules: true

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel 
          python -m pip install Django dask
          pip install --no-cache-dir -r requirements.txt

      - name: Configure Flake8 rules
        run: |
          echo "[flake8]" > .flake8
          echo "max-line-length = 120" >> .flake8
          echo "exclude = migrations,venv" >> .flake8
          echo "ignore = E203, E266, E501, W503" >> .flake8

      - name: Auto-format code with autopep8
        run: |
          pip install autopep8
          autopep8 --in-place --aggressive --aggressive -r .

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
        continue-on-error: true  # Ne bloque pas le pipeline en cas d'erreur

      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report

      - name: Run Django tests
        run: python manage.py test
